//
//  ProductionStrings.swift
//  Floreboard
//
//  【自动生成】请勿手改。来源：网页端 src/i18n/locales/*.json 的 productionSheet.*。
//  重新生成：node scripts/gen-ios-production-strings.mjs <本文件路径>
//
//  独立于 Localizable.xcstrings，避免与进行中的字符串目录改动冲突；键名与网页端一致，将来可平移进字符串目录。
//

import Foundation

enum ProductionStrings {
  /// 取当前语言的译文，缺失时依次回退英文、中文，最后返回键名；{{变量}} 会被替换。
  @MainActor
  static func t(_ key: String, _ args: [String: String] = [:]) -> String {
    let lang = LocalizationManager.shared.currentLanguage
    var value = table[lang]?[key] ?? table[.en]?[key] ?? table[.zh]?[key] ?? key
    for (k, v) in args { value = value.replacingOccurrences(of: "{{\(k)}}", with: v) }
    return value
  }

  private static let table: [Language: [String: String]] = [
    .zh: [
      "productionSheet.title": "制作稿",
      "productionSheet.stems": "共 {{n}} 枝",
      "productionSheet.minutes": "预计 {{n}} 分钟",
      "productionSheet.recipe": "配方表",
      "productionSheet.col.flower": "花材",
      "productionSheet.col.role": "角色",
      "productionSheet.col.count": "数量",
      "productionSheet.col.length": "修剪长度",
      "productionSheet.col.stock": "库存",
      "productionSheet.col.cost": "成本",
      "productionSheet.role.main": "主花",
      "productionSheet.role.filler": "配花",
      "productionSheet.role.foliage": "叶材",
      "productionSheet.notInStock": "不在库存",
      "productionSheet.total": "合计",
      "productionSheet.retailHint": "零售价合计（仅供参考，按库存标价逐枝折算）",
      "productionSheet.checks": "制作前校验",
      "productionSheet.check.allGood": "库存、预算与配比均无明显问题",
      "productionSheet.check.stockShort": "{{name}} 库存不足：需要 {{need}} 枝，现有 {{have}} 枝（缺 {{short}}）",
      "productionSheet.check.notInInventory": "{{name}} 不在当前库存中（可能是 AI 推荐的花材），请先确认能否采购",
      "productionSheet.check.budgetOver": "材料成本 ¥{{cost}} 超出预算 ¥{{budget}}",
      "productionSheet.check.budgetUnder": "材料成本 ¥{{cost}} 不到成交价 ¥{{budget}} 的三成，可考虑提升品质",
      "productionSheet.check.lowMargin": "利润率仅 {{margin}}%，低于 35% 的常见线",
      "productionSheet.check.noMainFlower": "方案中没有主花，焦点可能不明确",
      "productionSheet.check.foliageHeavy": "配花和叶材占 {{pct}}%，主花偏少",
      "productionSheet.craft": "工艺要点",
      "productionSheet.container": "容器 / 包装",
      "productionSheet.mechanics": "固定方式",
      "productionSheet.prep": "备料与处理",
      "productionSheet.assembly": "扎束 / 插制顺序",
      "productionSheet.care": "养护与配送",
      "productionSheet.priceProfit": "成交价 → 利润 · 利润率",
    ],
    .en: [
      "productionSheet.title": "Production Sheet",
      "productionSheet.stems": "{{n}} stems",
      "productionSheet.minutes": "~{{n}} min",
      "productionSheet.recipe": "Recipe",
      "productionSheet.col.flower": "Flower",
      "productionSheet.col.role": "Role",
      "productionSheet.col.count": "Qty",
      "productionSheet.col.length": "Cut length",
      "productionSheet.col.stock": "In stock",
      "productionSheet.col.cost": "Cost",
      "productionSheet.role.main": "Focal",
      "productionSheet.role.filler": "Filler",
      "productionSheet.role.foliage": "Foliage",
      "productionSheet.notInStock": "Not in stock",
      "productionSheet.total": "Total",
      "productionSheet.retailHint": "Sum at shelf retail prices (reference only)",
      "productionSheet.checks": "Pre-production checks",
      "productionSheet.check.allGood": "No issues found with stock, budget or balance",
      "productionSheet.check.stockShort": "{{name}} is short: need {{need}}, have {{have}} (short {{short}})",
      "productionSheet.check.notInInventory": "{{name}} is not in your inventory (possibly an AI suggestion). Confirm you can source it",
      "productionSheet.check.budgetOver": "Material cost ¥{{cost}} exceeds budget ¥{{budget}}",
      "productionSheet.check.budgetUnder": "Material cost ¥{{cost}} is under 30% of the ¥{{budget}} price; consider upgrading",
      "productionSheet.check.lowMargin": "Profit margin is only {{margin}}%, below the usual 35% line",
      "productionSheet.check.noMainFlower": "No focal flowers in this design; the focal point may be unclear",
      "productionSheet.check.foliageHeavy": "Filler and foliage make up {{pct}}% of stems; few focal flowers",
      "productionSheet.craft": "Craft notes",
      "productionSheet.container": "Vessel / wrap",
      "productionSheet.mechanics": "Mechanics",
      "productionSheet.prep": "Prep & conditioning",
      "productionSheet.assembly": "Assembly order",
      "productionSheet.care": "Care & delivery",
      "productionSheet.priceProfit": "Quoted price → profit · margin",
    ],
    .ja: [
      "productionSheet.title": "制作シート",
      "productionSheet.stems": "計 {{n}} 本",
      "productionSheet.minutes": "約 {{n}} 分",
      "productionSheet.recipe": "レシピ",
      "productionSheet.col.flower": "花材",
      "productionSheet.col.role": "役割",
      "productionSheet.col.count": "本数",
      "productionSheet.col.length": "カット長",
      "productionSheet.col.stock": "在庫",
      "productionSheet.col.cost": "原価",
      "productionSheet.role.main": "主役花",
      "productionSheet.role.filler": "脇役花",
      "productionSheet.role.foliage": "グリーン",
      "productionSheet.notInStock": "在庫なし",
      "productionSheet.total": "合計",
      "productionSheet.retailHint": "小売価格での合計（参考。在庫の販売価格を1本ずつ換算）",
      "productionSheet.checks": "制作前チェック",
      "productionSheet.check.allGood": "在庫・予算・バランスに目立った問題はありません",
      "productionSheet.check.stockShort": "{{name}} の在庫が不足しています：必要 {{need}} 本、在庫 {{have}} 本（不足 {{short}} 本）",
      "productionSheet.check.notInInventory": "{{name}} は現在の在庫にありません（AI の提案かもしれません）。仕入れ可能か先に確認してください",
      "productionSheet.check.budgetOver": "材料原価 ¥{{cost}} が予算 ¥{{budget}} を超えています",
      "productionSheet.check.budgetUnder": "材料原価 ¥{{cost}} は販売価格 ¥{{budget}} の3割未満です。品質アップも検討できます",
      "productionSheet.check.lowMargin": "利益率が {{margin}}% で、一般的な目安の 35% を下回っています",
      "productionSheet.check.noMainFlower": "主役花がなく、焦点が曖昧になるかもしれません",
      "productionSheet.check.foliageHeavy": "脇役花とグリーンが {{pct}}% を占め、主役花が少なめです",
      "productionSheet.craft": "制作ポイント",
      "productionSheet.container": "花器／ラッピング",
      "productionSheet.mechanics": "固定方法",
      "productionSheet.prep": "下準備と水揚げ",
      "productionSheet.assembly": "束ねる／挿す順序",
      "productionSheet.care": "管理と配送",
      "productionSheet.priceProfit": "販売価格 → 利益・利益率",
    ],
    .ko: [
      "productionSheet.title": "제작 시트",
      "productionSheet.stems": "총 {{n}}대",
      "productionSheet.minutes": "약 {{n}}분",
      "productionSheet.recipe": "레시피",
      "productionSheet.col.flower": "꽃",
      "productionSheet.col.role": "역할",
      "productionSheet.col.count": "수량",
      "productionSheet.col.length": "커팅 길이",
      "productionSheet.col.stock": "재고",
      "productionSheet.col.cost": "원가",
      "productionSheet.role.main": "메인 꽃",
      "productionSheet.role.filler": "서브 꽃",
      "productionSheet.role.foliage": "그린",
      "productionSheet.notInStock": "재고 없음",
      "productionSheet.total": "합계",
      "productionSheet.retailHint": "소매가 합계 (참고용, 재고 판매가를 줄기별로 환산)",
      "productionSheet.checks": "제작 전 점검",
      "productionSheet.check.allGood": "재고, 예산, 구성에 눈에 띄는 문제가 없습니다",
      "productionSheet.check.stockShort": "{{name}} 재고 부족: 필요 {{need}}대, 보유 {{have}}대 ({{short}}대 부족)",
      "productionSheet.check.notInInventory": "{{name}}은(는) 현재 재고에 없습니다(AI가 추천한 꽃일 수 있어요). 먼저 구매 가능한지 확인하세요",
      "productionSheet.check.budgetOver": "재료 원가 ¥{{cost}}이(가) 예산 ¥{{budget}}을(를) 초과했습니다",
      "productionSheet.check.budgetUnder": "재료 원가 ¥{{cost}}이(가) 판매가 ¥{{budget}}의 30%도 되지 않습니다. 품질을 높이는 것도 고려해 보세요",
      "productionSheet.check.lowMargin": "이익률이 {{margin}}%로, 일반적인 기준인 35%보다 낮습니다",
      "productionSheet.check.noMainFlower": "메인 꽃이 없어 시선이 모이는 포인트가 불분명할 수 있습니다",
      "productionSheet.check.foliageHeavy": "서브 꽃과 그린이 {{pct}}%로, 메인 꽃이 적은 편입니다",
      "productionSheet.craft": "제작 포인트",
      "productionSheet.container": "화기 / 포장",
      "productionSheet.mechanics": "고정 방법",
      "productionSheet.prep": "손질과 준비",
      "productionSheet.assembly": "묶기 / 꽂는 순서",
      "productionSheet.care": "관리 및 배송",
      "productionSheet.priceProfit": "판매가 → 이익 · 이익률",
    ],
    .fr: [
      "productionSheet.title": "Fiche de fabrication",
      "productionSheet.stems": "{{n}} tiges",
      "productionSheet.minutes": "~{{n}} min",
      "productionSheet.recipe": "Recette",
      "productionSheet.col.flower": "Fleur",
      "productionSheet.col.role": "Rôle",
      "productionSheet.col.count": "Qté",
      "productionSheet.col.length": "Longueur de coupe",
      "productionSheet.col.stock": "En stock",
      "productionSheet.col.cost": "Coût",
      "productionSheet.role.main": "Fleur principale",
      "productionSheet.role.filler": "Fleur d'appoint",
      "productionSheet.role.foliage": "Feuillage",
      "productionSheet.notInStock": "Hors stock",
      "productionSheet.total": "Total",
      "productionSheet.retailHint": "Total aux prix de vente (indicatif, tige par tige)",
      "productionSheet.checks": "Contrôles avant fabrication",
      "productionSheet.check.allGood": "Aucun problème notable de stock, de budget ou d'équilibre",
      "productionSheet.check.stockShort": "Stock insuffisant pour {{name}} : {{need}} tiges nécessaires, {{have}} disponibles (manque {{short}})",
      "productionSheet.check.notInInventory": "{{name}} n'est pas dans votre stock (peut-être une suggestion de l'IA). Vérifiez que vous pouvez vous le procurer",
      "productionSheet.check.budgetOver": "Le coût matière de ¥{{cost}} dépasse le budget de ¥{{budget}}",
      "productionSheet.check.budgetUnder": "Le coût matière de ¥{{cost}} représente moins de 30 % du prix de ¥{{budget}} ; vous pouvez monter en gamme",
      "productionSheet.check.lowMargin": "La marge n'est que de {{margin}} %, sous le seuil habituel de 35 %",
      "productionSheet.check.noMainFlower": "Aucune fleur principale : le point focal risque d'être peu lisible",
      "productionSheet.check.foliageHeavy": "Les fleurs d'appoint et le feuillage représentent {{pct}} % ; peu de fleurs principales",
      "productionSheet.craft": "Points techniques",
      "productionSheet.container": "Contenant / emballage",
      "productionSheet.mechanics": "Méthode de fixation",
      "productionSheet.prep": "Préparation et conditionnement",
      "productionSheet.assembly": "Ordre de montage",
      "productionSheet.care": "Entretien et livraison",
      "productionSheet.priceProfit": "Prix de vente → bénéfice · marge",
    ],
  ]
}
