//
//  ProductionStrings.swift
//  Floreboard
//
//  【自动生成】请勿手改。来源：网页端 src/i18n/locales/*.json 的 productionSheet.* / knowledge.* / designDetail.evaluation.* / designDetail.share.*。
//  重新生成：node scripts/gen-ios-production-strings.mjs <本文件路径>
//
//  独立于 Localizable.xcstrings，避免与进行中的字符串目录改动冲突；键名与网页端一致，将来可平移进字符串目录。
//

import Foundation

enum ProductionStrings {
  /// 取当前语言的译文，缺失时依次回退英文、中文，最后返回键名；{{变量}} 会被替换。
  @MainActor
  static func t(_ key: String, _ args: [String: String] = [:]) -> String {
    let lang = LocalizationManager.shared.currentLanguage
    var value = table[lang]?[key] ?? table[.en]?[key] ?? table[.zh]?[key] ?? key
    for (k, v) in args { value = value.replacingOccurrences(of: "{{\(k)}}", with: v) }
    return value
  }

  private static let table: [Language: [String: String]] = [
    .zh: [
      "productionSheet.title": "制作稿",
      "productionSheet.stems": "共 {{n}} 枝",
      "productionSheet.minutes": "预计 {{n}} 分钟",
      "productionSheet.recipe": "配方表",
      "productionSheet.col.flower": "花材",
      "productionSheet.col.role": "角色",
      "productionSheet.col.count": "数量",
      "productionSheet.col.length": "修剪长度",
      "productionSheet.col.stock": "库存",
      "productionSheet.col.cost": "成本",
      "productionSheet.role.main": "主花",
      "productionSheet.role.filler": "配花",
      "productionSheet.role.foliage": "叶材",
      "productionSheet.notInStock": "不在库存",
      "productionSheet.total": "合计",
      "productionSheet.retailHint": "零售价合计（仅供参考，按库存标价逐枝折算）",
      "productionSheet.checks": "制作前校验",
      "productionSheet.check.allGood": "库存、预算与配比均无明显问题",
      "productionSheet.check.stockShort": "{{name}} 库存不足：需要 {{need}} 枝，现有 {{have}} 枝（缺 {{short}}）",
      "productionSheet.check.notInInventory": "{{name}} 不在当前库存中（可能是 AI 推荐的花材），请先确认能否采购",
      "productionSheet.check.budgetOver": "材料成本 ¥{{cost}} 超出预算 ¥{{budget}}",
      "productionSheet.check.budgetUnder": "材料成本 ¥{{cost}} 不到成交价 ¥{{budget}} 的三成，可考虑提升品质",
      "productionSheet.check.lowMargin": "利润率仅 {{margin}}%，低于 35% 的常见线",
      "productionSheet.check.noMainFlower": "方案中没有主花，焦点可能不明确",
      "productionSheet.check.foliageHeavy": "配花和叶材占 {{pct}}%，主花偏少",
      "productionSheet.craft": "工艺要点",
      "productionSheet.container": "容器 / 包装",
      "productionSheet.mechanics": "固定方式",
      "productionSheet.prep": "备料与处理",
      "productionSheet.assembly": "扎束 / 插制顺序",
      "productionSheet.care": "养护与配送",
      "productionSheet.priceProfit": "成交价 → 利润 · 利润率",
      "knowledge.title": "专业校验",
      "knowledge.subtitle": "基于流派、场合与花材知识的规则检查，作为参考建议",
      "knowledge.loading": "校验中…",
      "knowledge.allClear": "未发现明显的流派、文化或配比问题",
      "knowledge.school.japanese_ikenobo": "池坊流",
      "knowledge.school.japanese_ohara": "小原流",
      "knowledge.school.japanese_sogetsu": "草月流",
      "knowledge.school.chinese_literati": "中式文人花",
      "knowledge.school.chinese_zen": "中式禅花",
      "knowledge.school.western_biedermeier": "比德迈尔",
      "knowledge.school.western_english": "英式花园风",
      "knowledge.school.fusion": "融合创意",
      "knowledge.season.spring": "春季",
      "knowledge.season.summer": "夏季",
      "knowledge.season.autumn": "秋季",
      "knowledge.season.winter": "冬季",
      "knowledge.rule.focalTypesMany": "主花有 {{n}} 种，焦点容易互相抢戏；专业做法通常把主花控制在 3 种以内，其余作配花或叶材",
      "knowledge.rule.noSupport": "全是主花，没有配花或叶材收边，层次与呼吸感不足",
      "knowledge.rule.noFoliage": "没有叶材，建议加入叶材衬托并收束轮廓",
      "knowledge.rule.mixedVaseLife": "{{name}} 水养寿命约 {{days}} 天，明显短于其他花材，建议当天或次日交付，并提醒客户尽快欣赏",
      "knowledge.rule.outOfSeason": "{{names}} 不在{{season}}当季，成本可能偏高或品质不稳定",
      "knowledge.rule.paletteBusy": "色彩多达 {{n}} 个色系，容易显得杂乱，可收敛为 2–3 个主色系",
      "knowledge.rule.tabooChrysanthemum": "{{names}}（白色/黄色菊花）在不少地区与丧礼相关，不太适合喜庆场合",
      "knowledge.rule.strongScentComfort": "{{names}} 香气浓郁，不适合探病或慰问场合",
      "knowledge.rule.tabooFour": "{{names}} 的数量是 4，“4”与“死”谐音，作为礼物常被避讳，可调整为 3 或 5",
      "knowledge.rule.tabooFourTotal": "总枝数是 4，“4”与“死”谐音，作为礼物常被避讳",
      "knowledge.rule.schoolTooFewStems": "{{school}}通常不少于 {{min}} 枝才能成型，目前只有 {{n}} 枝",
      "knowledge.rule.schoolTooManyStems": "{{school}}讲究克制，通常不超过 {{max}} 枝，目前 {{n}} 枝",
      "knowledge.rule.schoolTypesMany": "{{school}}宜控制花材种类（不超过 {{max}} 种），目前 {{n}} 种",
      "knowledge.rule.schoolTypesFew": "{{school}}强调丰富的混搭，建议至少 {{min}} 种，目前 {{n}} 种",
      "knowledge.rule.schoolNeedsFoliage": "{{school}}通常配有叶材（围边或穿插），目前没有",
      "knowledge.rule.kbCoverage": "以下花材暂未收录在知识库中，花期、当季、香气类提示对它们不生效：{{names}}",
      "knowledge.rule.petToxicSevere": "{{names}} 对猫有剧毒（花瓣、花粉、花瓶水都危险），有养猫的家庭请勿送出或摆放",
      "knowledge.rule.petToxic": "{{names}} 对猫狗有一定毒性，送给有宠物的客户时请提醒其放在宠物够不到的地方",
      "knowledge.rule.sapNarcissus": "{{name}} 的切口黏液会堵塞其他花材导管、缩短整体花期；需先单独养护 12–24 小时再混插，且不要剪后马上与其他花同瓶",
      "knowledge.rule.pollenStain": "{{names}} 的花粉易沾染婚纱和衣物；建议制作时摘除花药",
      "knowledge.rule.clientPetToxic": "客户家里养猫，{{names}} 对猫有剧毒，必须替换",
      "knowledge.rule.clientPetToxicMild": "客户家里有宠物，{{names}} 对猫狗有一定毒性，建议替换，或提醒放在宠物够不到的地方",
      "knowledge.rule.clientAvoid": "{{names}} 是该客户明确不要的花材",
      "knowledge.rule.clientScent": "该客户对浓香敏感，{{names}} 香气浓郁",
      "knowledge.rule.clientPollen": "该客户对花粉敏感，{{names}} 花粉量大，建议替换或摘除花药",
      "knowledge.rule.holidayPriceSurge": "距{{holiday}}还有 {{days}} 天：{{names}} 节前批发价通常涨到平日的 {{low}}–{{high}} 倍，建议提前锁价备货，并按节日价报价",
      "knowledge.rule.tabooNine": "{{names}} 的数量是 9：在日语里“9”与“苦”同音，日本送礼时常被避讳，可调整为 7 或 11",
      "knowledge.rule.tabooNineTotal": "总数是 9 枝：在日语里“9”与“苦”同音，日本送礼时常被避讳",
      "knowledge.badge.title": "专业校验：{{error}} 项严重，{{warn}} 项建议，{{info}} 项提示",
      "knowledge.holiday.valentine": "情人节",
      "knowledge.holiday.spring_festival": "春节",
      "knowledge.holiday.womens_day": "妇女节",
      "knowledge.holiday.white_day": "白色情人节",
      "knowledge.holiday.qingming": "清明",
      "knowledge.holiday.mothers_day": "母亲节",
      "knowledge.holiday.parents_day": "父母节",
      "knowledge.holiday.may20": "520",
      "knowledge.holiday.qixi": "七夕",
      "knowledge.holiday.teachers_day": "教师节",
      "knowledge.holiday.christmas": "圣诞节",
      "designDetail.evaluation.title": "方案评价",
      "designDetail.evaluation.rating": "评分",
      "designDetail.evaluation.feedback": "心得 / 客户反馈",
      "designDetail.evaluation.placeholder": "记录客户的反馈，或设计过程中的心得...",
      "designDetail.evaluation.saveBtn": "保存评价",
      "designDetail.share.button": "发给客户",
      "designDetail.share.title": "分享方案给客户",
      "designDetail.share.hint": "把链接发给客户（微信、短信均可）。客户无需注册即可查看，并能直接“确认”或“提出调整”。",
      "designDetail.share.showPrice": "在分享页显示报价",
      "designDetail.share.privacy": "分享页只显示效果图、花材与数量、文案和店名；成本、利润与客户信息不会出现，页面也不会被搜索引擎收录。",
      "designDetail.share.revoke": "撤销链接",
      "designDetail.share.revoked": "链接已撤销，旧链接立即失效",
      "designDetail.share.done": "完成",
      "designDetail.share.failed": "生成分享链接失败，请稍后重试",
      "designDetail.share.copyFailed": "复制失败，请手动复制链接",
      "designDetail.share.clientApproved": "客户已确认这个方案",
      "designDetail.share.clientChanges": "客户希望调整",
    ],
    .en: [
      "productionSheet.title": "Production Sheet",
      "productionSheet.stems": "{{n}} stems",
      "productionSheet.minutes": "~{{n}} min",
      "productionSheet.recipe": "Recipe",
      "productionSheet.col.flower": "Flower",
      "productionSheet.col.role": "Role",
      "productionSheet.col.count": "Qty",
      "productionSheet.col.length": "Cut length",
      "productionSheet.col.stock": "In stock",
      "productionSheet.col.cost": "Cost",
      "productionSheet.role.main": "Focal",
      "productionSheet.role.filler": "Filler",
      "productionSheet.role.foliage": "Foliage",
      "productionSheet.notInStock": "Not in stock",
      "productionSheet.total": "Total",
      "productionSheet.retailHint": "Sum at shelf retail prices (reference only)",
      "productionSheet.checks": "Pre-production checks",
      "productionSheet.check.allGood": "No issues found with stock, budget or balance",
      "productionSheet.check.stockShort": "{{name}} is short: need {{need}}, have {{have}} (short {{short}})",
      "productionSheet.check.notInInventory": "{{name}} is not in your inventory (possibly an AI suggestion). Confirm you can source it",
      "productionSheet.check.budgetOver": "Material cost ¥{{cost}} exceeds budget ¥{{budget}}",
      "productionSheet.check.budgetUnder": "Material cost ¥{{cost}} is under 30% of the ¥{{budget}} price; consider upgrading",
      "productionSheet.check.lowMargin": "Profit margin is only {{margin}}%, below the usual 35% line",
      "productionSheet.check.noMainFlower": "No focal flowers in this design; the focal point may be unclear",
      "productionSheet.check.foliageHeavy": "Filler and foliage make up {{pct}}% of stems; few focal flowers",
      "productionSheet.craft": "Craft notes",
      "productionSheet.container": "Vessel / wrap",
      "productionSheet.mechanics": "Mechanics",
      "productionSheet.prep": "Prep & conditioning",
      "productionSheet.assembly": "Assembly order",
      "productionSheet.care": "Care & delivery",
      "productionSheet.priceProfit": "Quoted price → profit · margin",
      "knowledge.title": "Design Review",
      "knowledge.subtitle": "Rule checks based on style school, occasion and flower knowledge (advisory)",
      "knowledge.loading": "Checking…",
      "knowledge.allClear": "No obvious school, cultural or balance issues found",
      "knowledge.school.japanese_ikenobo": "Ikenobo",
      "knowledge.school.japanese_ohara": "Ohara",
      "knowledge.school.japanese_sogetsu": "Sogetsu",
      "knowledge.school.chinese_literati": "Chinese literati style",
      "knowledge.school.chinese_zen": "Chinese zen style",
      "knowledge.school.western_biedermeier": "Biedermeier",
      "knowledge.school.western_english": "English garden style",
      "knowledge.school.fusion": "Fusion",
      "knowledge.season.spring": "spring",
      "knowledge.season.summer": "summer",
      "knowledge.season.autumn": "autumn",
      "knowledge.season.winter": "winter",
      "knowledge.rule.focalTypesMany": "{{n}} focal flower types will compete for attention; designers usually keep focal flowers to 3 types or fewer and use the rest as filler or foliage",
      "knowledge.rule.noSupport": "All focal flowers with no filler or foliage to support and finish the shape",
      "knowledge.rule.noFoliage": "No foliage; adding some will frame the arrangement and define its outline",
      "knowledge.rule.mixedVaseLife": "{{name}} lasts only about {{days}} days, much shorter than the rest; deliver same or next day and tell the client to enjoy it soon",
      "knowledge.rule.outOfSeason": "{{names}} is out of season for {{season}}; cost may run high or quality may vary",
      "knowledge.rule.paletteBusy": "{{n}} colour families may look cluttered; consider narrowing to 2–3 main families",
      "knowledge.rule.tabooChrysanthemum": "{{names}} (white/yellow chrysanthemum) is associated with funerals in many regions and is a poor fit for a joyful occasion",
      "knowledge.rule.strongScentComfort": "{{names}} is strongly scented and not suited to a sick-visit or condolence occasion",
      "knowledge.rule.tabooFour": "{{names}} is used in a quantity of 4; \"4\" sounds like \"death\" in Chinese/Japanese/Korean, so gifts of 4 are often avoided — consider 3 or 5",
      "knowledge.rule.tabooFourTotal": "The total is 4 stems; \"4\" sounds like \"death\" in Chinese/Japanese/Korean, so gifts of 4 are often avoided",
      "knowledge.rule.schoolTooFewStems": "{{school}} usually needs at least {{min}} stems to hold its form; this has only {{n}}",
      "knowledge.rule.schoolTooManyStems": "{{school}} favours restraint, typically no more than {{max}} stems; this has {{n}}",
      "knowledge.rule.schoolTypesMany": "{{school}} works best with few flower types (at most {{max}}); this has {{n}}",
      "knowledge.rule.schoolTypesFew": "{{school}} is about rich mixing; aim for at least {{min}} types, this has {{n}}",
      "knowledge.rule.schoolNeedsFoliage": "{{school}} normally includes foliage (as a collar or woven through); this has none",
      "knowledge.rule.kbCoverage": "These flowers are not in the knowledge base yet, so season, vase-life and scent checks don't apply to them: {{names}}",
      "knowledge.rule.petToxicSevere": "{{names}} is highly toxic to cats (petals, pollen and even vase water can be dangerous); do not give or place it in a home with cats",
      "knowledge.rule.petToxic": "{{names}} is mildly toxic to cats and dogs; remind clients with pets to keep it out of reach",
      "knowledge.rule.sapNarcissus": "The cut-stem sap of {{name}} clogs other flowers' stems and shortens vase life; condition it on its own for 12–24 hours before mixing, and never put freshly cut stems straight in with other flowers",
      "knowledge.rule.pollenStain": "The pollen of {{names}} stains gowns and clothing easily; remove the anthers when making the piece",
      "knowledge.rule.clientPetToxic": "The client has cats and {{names}} is highly toxic to cats; it must be replaced",
      "knowledge.rule.clientPetToxicMild": "The client has pets and {{names}} is mildly toxic to cats and dogs; consider replacing it, or remind them to keep it out of reach",
      "knowledge.rule.clientAvoid": "The client has said they do not want {{names}}",
      "knowledge.rule.clientScent": "The client is sensitive to strong fragrance and {{names}} is strongly scented",
      "knowledge.rule.clientPollen": "The client is sensitive to pollen and {{names}} sheds a lot of it; replace it or remove the anthers",
      "knowledge.rule.holidayPriceSurge": "{{holiday}} is {{days}} day(s) away: wholesale prices of {{names}} usually run {{low}}–{{high}}× normal before it — lock in stock early and quote at holiday prices",
      "knowledge.rule.tabooNine": "{{names}} is used in a quantity of 9; in Japanese \"9\" (ku) sounds like \"suffering\", so gifts of 9 are often avoided in Japan — consider 7 or 11",
      "knowledge.rule.tabooNineTotal": "The total is 9 stems; in Japanese \"9\" (ku) sounds like \"suffering\", so gifts of 9 are often avoided in Japan",
      "knowledge.badge.title": "Design review: {{error}} critical, {{warn}} suggestions, {{info}} notes",
      "knowledge.holiday.valentine": "Valentine's Day",
      "knowledge.holiday.spring_festival": "Chinese New Year",
      "knowledge.holiday.womens_day": "Women's Day",
      "knowledge.holiday.white_day": "White Day",
      "knowledge.holiday.qingming": "Qingming",
      "knowledge.holiday.mothers_day": "Mother's Day",
      "knowledge.holiday.parents_day": "Parents' Day",
      "knowledge.holiday.may20": "520 (May 20)",
      "knowledge.holiday.qixi": "Qixi",
      "knowledge.holiday.teachers_day": "Teachers' Day",
      "knowledge.holiday.christmas": "Christmas",
      "designDetail.evaluation.title": "Evaluation",
      "designDetail.evaluation.rating": "Rating",
      "designDetail.evaluation.feedback": "Feedback / Notes",
      "designDetail.evaluation.placeholder": "Record client feedback or design notes...",
      "designDetail.evaluation.saveBtn": "Save Evaluation",
      "designDetail.share.button": "Send to client",
      "designDetail.share.title": "Share this design with your client",
      "designDetail.share.hint": "Send the link by message or email. Your client can view it without signing up and approve it or ask for changes right there.",
      "designDetail.share.showPrice": "Show the quote on the shared page",
      "designDetail.share.privacy": "The shared page shows only the image, flowers and quantities, the text and your shop name. Costs, margins and client details never appear, and the page is hidden from search engines.",
      "designDetail.share.revoke": "Revoke link",
      "designDetail.share.revoked": "Link revoked — the old link stops working immediately",
      "designDetail.share.done": "Done",
      "designDetail.share.failed": "Could not create the share link. Please try again.",
      "designDetail.share.copyFailed": "Copy failed — please copy the link manually",
      "designDetail.share.clientApproved": "Your client approved this design",
      "designDetail.share.clientChanges": "Your client asked for changes",
    ],
    .ja: [
      "productionSheet.title": "制作シート",
      "productionSheet.stems": "計 {{n}} 本",
      "productionSheet.minutes": "約 {{n}} 分",
      "productionSheet.recipe": "レシピ",
      "productionSheet.col.flower": "花材",
      "productionSheet.col.role": "役割",
      "productionSheet.col.count": "本数",
      "productionSheet.col.length": "カット長",
      "productionSheet.col.stock": "在庫",
      "productionSheet.col.cost": "原価",
      "productionSheet.role.main": "主役花",
      "productionSheet.role.filler": "脇役花",
      "productionSheet.role.foliage": "グリーン",
      "productionSheet.notInStock": "在庫なし",
      "productionSheet.total": "合計",
      "productionSheet.retailHint": "小売価格での合計（参考。在庫の販売価格を1本ずつ換算）",
      "productionSheet.checks": "制作前チェック",
      "productionSheet.check.allGood": "在庫・予算・バランスに目立った問題はありません",
      "productionSheet.check.stockShort": "{{name}} の在庫が不足しています：必要 {{need}} 本、在庫 {{have}} 本（不足 {{short}} 本）",
      "productionSheet.check.notInInventory": "{{name}} は現在の在庫にありません（AI の提案かもしれません）。仕入れ可能か先に確認してください",
      "productionSheet.check.budgetOver": "材料原価 ¥{{cost}} が予算 ¥{{budget}} を超えています",
      "productionSheet.check.budgetUnder": "材料原価 ¥{{cost}} は販売価格 ¥{{budget}} の3割未満です。品質アップも検討できます",
      "productionSheet.check.lowMargin": "利益率が {{margin}}% で、一般的な目安の 35% を下回っています",
      "productionSheet.check.noMainFlower": "主役花がなく、焦点が曖昧になるかもしれません",
      "productionSheet.check.foliageHeavy": "脇役花とグリーンが {{pct}}% を占め、主役花が少なめです",
      "productionSheet.craft": "制作ポイント",
      "productionSheet.container": "花器／ラッピング",
      "productionSheet.mechanics": "固定方法",
      "productionSheet.prep": "下準備と水揚げ",
      "productionSheet.assembly": "束ねる／挿す順序",
      "productionSheet.care": "管理と配送",
      "productionSheet.priceProfit": "販売価格 → 利益・利益率",
      "knowledge.title": "デザインレビュー",
      "knowledge.subtitle": "流派・シーン・花材の知識に基づくルールチェック（参考アドバイス）",
      "knowledge.loading": "チェック中…",
      "knowledge.allClear": "流派・文化・バランス面で目立った問題は見つかりませんでした",
      "knowledge.season.spring": "春",
      "knowledge.season.summer": "夏",
      "knowledge.season.autumn": "秋",
      "knowledge.season.winter": "冬",
      "knowledge.rule.focalTypesMany": "主役花が {{n}} 種類あり、視線の焦点が競合しがちです。プロは主役花を 3 種類以内に絞り、残りは脇役花やグリーンにします",
      "knowledge.rule.noSupport": "主役花だけで、脇役花やグリーンによる支えと仕上げがありません。奥行きと軽やかさが不足します",
      "knowledge.rule.noFoliage": "グリーンがありません。グリーンを加えると輪郭が引き締まります",
      "knowledge.rule.mixedVaseLife": "{{name}} の水揚げ寿命は約 {{days}} 日で、他の花材よりかなり短めです。当日か翌日の納品をおすすめし、お客様に早めに楽しんでもらうようお伝えください",
      "knowledge.rule.outOfSeason": "{{names}} は{{season}}の旬ではありません。コストが高くなったり品質が安定しない場合があります",
      "knowledge.rule.paletteBusy": "色が {{n}} 系統もあり、散らかった印象になりがちです。2〜3 系統に絞ることをおすすめします",
      "knowledge.rule.tabooChrysanthemum": "{{names}}（白・黄の菊）は多くの地域で弔事を連想させるため、お祝いの場面にはあまり向きません",
      "knowledge.rule.strongScentComfort": "{{names}} は香りが強いため、お見舞いやお悔やみの場面には向きません",
      "knowledge.rule.tabooFour": "{{names}} が 4 本です。中国語・日本語・韓国語では「4」が「死」を連想させるため、贈り物では避けられがちです。3 本か 5 本への変更をご検討ください",
      "knowledge.rule.tabooFourTotal": "合計が 4 本です。「4」は「死」を連想させるため、贈り物では避けられがちです",
      "knowledge.rule.schoolTooFewStems": "{{school}}では通常 {{min}} 本以上ないと形が整いません。現在は {{n}} 本です",
      "knowledge.rule.schoolTooManyStems": "{{school}}は引き算の美学を重んじ、通常 {{max}} 本以内に収めます。現在は {{n}} 本です",
      "knowledge.rule.schoolTypesMany": "{{school}}は花材の種類を絞るのが基本です（{{max}} 種類まで）。現在は {{n}} 種類です",
      "knowledge.rule.schoolTypesFew": "{{school}}は多彩な取り合わせが魅力です。{{min}} 種類以上をおすすめします。現在は {{n}} 種類です",
      "knowledge.rule.schoolNeedsFoliage": "{{school}}では通常グリーンを添えます（縁取りや差し込み）。現在はありません",
      "knowledge.rule.kbCoverage": "次の花材は知識ベースに未登録のため、旬・花持ち・香りに関するチェックの対象外です：{{names}}",
      "knowledge.rule.petToxicSevere": "{{names}} は猫にとって猛毒です（花びら・花粉・花瓶の水も危険）。猫のいるご家庭へのお届けや飾りつけは避けてください",
      "knowledge.rule.petToxic": "{{names}} は猫や犬に対して軽い毒性があります。ペットのいるお客様には、手の届かない場所に飾るようお伝えください",
      "knowledge.rule.sapNarcissus": "{{name}} の切り口から出る粘液は他の花の導管を詰まらせ、花持ちを縮めます。混ぜる前に12〜24時間単独で水揚げし、切りたてをそのまま他の花と一緒に活けないでください",
      "knowledge.rule.pollenStain": "{{names}} の花粉はドレスや衣服に付きやすいため、制作時に葯を取り除くことをおすすめします",
      "knowledge.rule.clientPetToxic": "お客様は猫を飼っており、{{names}} は猫に猛毒です。必ず差し替えてください",
      "knowledge.rule.clientPetToxicMild": "お客様はペットを飼っており、{{names}} は猫や犬に軽い毒性があります。差し替えるか、手の届かない場所に飾るようお伝えください",
      "knowledge.rule.clientAvoid": "{{names}} はこのお客様が望まない花材です",
      "knowledge.rule.clientScent": "このお客様は強い香りが苦手で、{{names}} は香りが強い花です",
      "knowledge.rule.clientPollen": "このお客様は花粉に敏感で、{{names}} は花粉が多い花です。差し替えるか葯を取り除いてください",
      "knowledge.rule.holidayPriceSurge": "{{holiday}}まであと {{days}} 日：{{names}} の仕入れ値は通常の {{low}}〜{{high}} 倍になりがちです。早めに仕入れを確保し、繁忙期価格でお見積もりください",
      "knowledge.rule.tabooNine": "{{names}} が 9 本です。「9（く）」は「苦」を連想させるため、贈り物では避けられがちです。7 本か 11 本への変更をご検討ください",
      "knowledge.rule.tabooNineTotal": "合計 9 本です。「9（く）」は「苦」を連想させるため、贈り物では避けられがちです",
      "knowledge.school.japanese_ikenobo": "池坊",
      "knowledge.school.japanese_ohara": "小原流",
      "knowledge.school.japanese_sogetsu": "草月流",
      "knowledge.school.chinese_literati": "文人花",
      "knowledge.school.chinese_zen": "禅花",
      "knowledge.school.western_biedermeier": "ビーダーマイヤー",
      "knowledge.school.western_english": "イングリッシュガーデン",
      "knowledge.school.fusion": "フュージョン",
      "knowledge.badge.title": "デザインレビュー：重大 {{error}} 件、提案 {{warn}} 件、参考 {{info}} 件",
      "knowledge.holiday.valentine": "バレンタインデー",
      "knowledge.holiday.spring_festival": "春節",
      "knowledge.holiday.womens_day": "国際女性デー",
      "knowledge.holiday.white_day": "ホワイトデー",
      "knowledge.holiday.qingming": "清明節",
      "knowledge.holiday.mothers_day": "母の日",
      "knowledge.holiday.parents_day": "父母の日",
      "knowledge.holiday.may20": "520（5月20日）",
      "knowledge.holiday.qixi": "七夕（中国）",
      "knowledge.holiday.teachers_day": "教師の日",
      "knowledge.holiday.christmas": "クリスマス",
      "designDetail.evaluation.title": "プラン評価",
      "designDetail.evaluation.rating": "評価",
      "designDetail.evaluation.feedback": "メモ / 顧客フィードバック",
      "designDetail.evaluation.placeholder": "お客様の反応や、デザイン時のメモを記録...",
      "designDetail.evaluation.saveBtn": "評価を保存",
      "designDetail.share.button": "お客様に送る",
      "designDetail.share.title": "デザインをお客様に共有",
      "designDetail.share.hint": "リンクをメッセージやメールで送ってください。お客様は登録なしで閲覧でき、その場で「承認」または「修正依頼」ができます。",
      "designDetail.share.showPrice": "共有ページにお見積もりを表示",
      "designDetail.share.privacy": "共有ページには画像、花材と本数、説明文、店名のみが表示されます。原価・利益・顧客情報は表示されず、検索エンジンにも登録されません。",
      "designDetail.share.revoke": "リンクを無効化",
      "designDetail.share.revoked": "リンクを無効化しました。以前のリンクはすぐに使えなくなります",
      "designDetail.share.done": "完了",
      "designDetail.share.failed": "共有リンクを作成できませんでした。もう一度お試しください。",
      "designDetail.share.copyFailed": "コピーできませんでした。手動でコピーしてください",
      "designDetail.share.clientApproved": "お客様がこのデザインを承認しました",
      "designDetail.share.clientChanges": "お客様から修正の依頼があります",
    ],
    .ko: [
      "productionSheet.title": "제작 시트",
      "productionSheet.stems": "총 {{n}}대",
      "productionSheet.minutes": "약 {{n}}분",
      "productionSheet.recipe": "레시피",
      "productionSheet.col.flower": "꽃",
      "productionSheet.col.role": "역할",
      "productionSheet.col.count": "수량",
      "productionSheet.col.length": "커팅 길이",
      "productionSheet.col.stock": "재고",
      "productionSheet.col.cost": "원가",
      "productionSheet.role.main": "메인 꽃",
      "productionSheet.role.filler": "서브 꽃",
      "productionSheet.role.foliage": "그린",
      "productionSheet.notInStock": "재고 없음",
      "productionSheet.total": "합계",
      "productionSheet.retailHint": "소매가 합계 (참고용, 재고 판매가를 줄기별로 환산)",
      "productionSheet.checks": "제작 전 점검",
      "productionSheet.check.allGood": "재고, 예산, 구성에 눈에 띄는 문제가 없습니다",
      "productionSheet.check.stockShort": "{{name}} 재고 부족: 필요 {{need}}대, 보유 {{have}}대 ({{short}}대 부족)",
      "productionSheet.check.notInInventory": "{{name}}은(는) 현재 재고에 없습니다(AI가 추천한 꽃일 수 있어요). 먼저 구매 가능한지 확인하세요",
      "productionSheet.check.budgetOver": "재료 원가 ¥{{cost}}이(가) 예산 ¥{{budget}}을(를) 초과했습니다",
      "productionSheet.check.budgetUnder": "재료 원가 ¥{{cost}}이(가) 판매가 ¥{{budget}}의 30%도 되지 않습니다. 품질을 높이는 것도 고려해 보세요",
      "productionSheet.check.lowMargin": "이익률이 {{margin}}%로, 일반적인 기준인 35%보다 낮습니다",
      "productionSheet.check.noMainFlower": "메인 꽃이 없어 시선이 모이는 포인트가 불분명할 수 있습니다",
      "productionSheet.check.foliageHeavy": "서브 꽃과 그린이 {{pct}}%로, 메인 꽃이 적은 편입니다",
      "productionSheet.craft": "제작 포인트",
      "productionSheet.container": "화기 / 포장",
      "productionSheet.mechanics": "고정 방법",
      "productionSheet.prep": "손질과 준비",
      "productionSheet.assembly": "묶기 / 꽂는 순서",
      "productionSheet.care": "관리 및 배송",
      "productionSheet.priceProfit": "판매가 → 이익 · 이익률",
      "knowledge.title": "디자인 리뷰",
      "knowledge.subtitle": "유파, 상황, 꽃 지식에 기반한 규칙 점검 (참고용 조언)",
      "knowledge.loading": "점검 중…",
      "knowledge.allClear": "유파, 문화, 구성 면에서 눈에 띄는 문제가 없습니다",
      "knowledge.season.spring": "봄",
      "knowledge.season.summer": "여름",
      "knowledge.season.autumn": "가을",
      "knowledge.season.winter": "겨울",
      "knowledge.rule.focalTypesMany": "메인 꽃이 {{n}}종이라 시선이 분산되기 쉽습니다. 전문가는 보통 메인 꽃을 3종 이내로 줄이고 나머지는 서브 꽃이나 그린으로 씁니다",
      "knowledge.rule.noSupport": "메인 꽃만 있고 받쳐 주는 서브 꽃이나 그린이 없어 입체감과 여유가 부족합니다",
      "knowledge.rule.noFoliage": "그린이 없습니다. 그린을 더하면 윤곽이 또렷해집니다",
      "knowledge.rule.mixedVaseLife": "{{name}}은(는) 수명이 약 {{days}}일로 다른 꽃보다 훨씬 짧습니다. 당일 또는 다음 날 전달을 권하고, 고객에게 빨리 감상하시라고 안내하세요",
      "knowledge.rule.outOfSeason": "{{names}}은(는) {{season}} 제철이 아니어서 원가가 높거나 품질이 일정하지 않을 수 있습니다",
      "knowledge.rule.paletteBusy": "색 계열이 {{n}}가지나 되어 산만해 보일 수 있습니다. 2~3가지 주요 색으로 줄여 보세요",
      "knowledge.rule.tabooChrysanthemum": "{{names}}(흰색/노란색 국화)은(는) 많은 지역에서 장례를 연상시켜 축하 자리에는 어울리지 않습니다",
      "knowledge.rule.strongScentComfort": "{{names}}은(는) 향이 강해 병문안이나 조문 자리에는 맞지 않습니다",
      "knowledge.rule.tabooFour": "{{names}}이(가) 4대입니다. 한국어·중국어·일본어에서 ‘4’는 ‘죽음’을 연상시켜 선물에서는 흔히 피합니다. 3대나 5대로 바꿔 보세요",
      "knowledge.rule.tabooFourTotal": "총 4대입니다. ‘4’는 ‘죽음’을 연상시켜 선물에서는 흔히 피합니다",
      "knowledge.rule.schoolTooFewStems": "{{school}}은(는) 보통 {{min}}대 이상은 있어야 형태가 잡힙니다. 현재 {{n}}대입니다",
      "knowledge.rule.schoolTooManyStems": "{{school}}은(는) 절제를 중시하며 보통 {{max}}대 이내로 합니다. 현재 {{n}}대입니다",
      "knowledge.rule.schoolTypesMany": "{{school}}은(는) 꽃 종류를 적게 쓰는 것이 기본입니다({{max}}종 이내). 현재 {{n}}종입니다",
      "knowledge.rule.schoolTypesFew": "{{school}}은(는) 다양한 조합이 매력입니다. {{min}}종 이상을 권합니다. 현재 {{n}}종입니다",
      "knowledge.rule.schoolNeedsFoliage": "{{school}}에는 보통 그린을 곁들입니다(둘레 장식이나 사이사이 꽂기). 현재는 없습니다",
      "knowledge.rule.kbCoverage": "다음 꽃은 지식 베이스에 아직 없어 제철·수명·향 관련 점검에서 제외되었습니다: {{names}}",
      "knowledge.rule.petToxicSevere": "{{names}}은(는) 고양이에게 치명적인 독성이 있습니다(꽃잎·꽃가루·꽃병 물도 위험). 고양이를 키우는 가정에는 선물하거나 두지 마세요",
      "knowledge.rule.petToxic": "{{names}}은(는) 고양이와 강아지에게 약한 독성이 있습니다. 반려동물이 있는 고객께는 손이 닿지 않는 곳에 두도록 안내해 주세요",
      "knowledge.rule.sapNarcissus": "{{name}}의 절단면 진액은 다른 꽃의 물관을 막아 수명을 단축시킵니다. 섞기 전에 12~24시간 따로 물올림을 하고, 자른 직후 다른 꽃과 함께 꽂지 마세요",
      "knowledge.rule.pollenStain": "{{names}}의 꽃가루는 웨딩드레스나 옷에 쉽게 묻습니다. 제작할 때 꽃밥을 제거하는 것을 권장합니다",
      "knowledge.rule.clientPetToxic": "고객이 고양이를 키우며 {{names}}은(는) 고양이에게 치명적입니다. 반드시 교체하세요",
      "knowledge.rule.clientPetToxicMild": "고객이 반려동물을 키우며 {{names}}은(는) 고양이와 강아지에게 약한 독성이 있습니다. 교체하거나 손이 닿지 않는 곳에 두도록 안내하세요",
      "knowledge.rule.clientAvoid": "{{names}}은(는) 이 고객이 원하지 않는 꽃입니다",
      "knowledge.rule.clientScent": "이 고객은 강한 향에 민감하며 {{names}}은(는) 향이 강합니다",
      "knowledge.rule.clientPollen": "이 고객은 꽃가루에 민감하며 {{names}}은(는) 꽃가루가 많습니다. 교체하거나 꽃밥을 제거하세요",
      "knowledge.rule.holidayPriceSurge": "{{holiday}}까지 {{days}}일 남았습니다. {{names}}의 도매가는 평소의 {{low}}~{{high}}배로 오르는 경우가 많으니, 미리 물량을 확보하고 시즌 가격으로 견적을 내세요",
      "knowledge.rule.tabooNine": "{{names}}이(가) 9대입니다. 일본어에서 ‘9(く)’는 ‘괴로움(苦)’과 발음이 같아 일본에서는 선물로 피하는 경우가 많습니다. 7대나 11대로 바꿔 보세요",
      "knowledge.rule.tabooNineTotal": "합계 9대입니다. 일본어에서 ‘9(く)’는 ‘괴로움(苦)’과 발음이 같아 일본에서는 선물로 피하는 경우가 많습니다",
      "knowledge.school.japanese_ikenobo": "이케노보 (입화)",
      "knowledge.school.japanese_ohara": "오하라류",
      "knowledge.school.japanese_sogetsu": "소게츠류",
      "knowledge.school.chinese_literati": "문인화",
      "knowledge.school.chinese_zen": "선화 (禪花)",
      "knowledge.school.western_biedermeier": "비더마이어",
      "knowledge.school.western_english": "잉글리시 가든",
      "knowledge.school.fusion": "퓨전",
      "knowledge.badge.title": "디자인 리뷰: 중요 {{error}}건, 제안 {{warn}}건, 참고 {{info}}건",
      "knowledge.holiday.valentine": "밸런타인데이",
      "knowledge.holiday.spring_festival": "춘절",
      "knowledge.holiday.womens_day": "세계 여성의 날",
      "knowledge.holiday.white_day": "화이트데이",
      "knowledge.holiday.qingming": "청명절",
      "knowledge.holiday.mothers_day": "어머니의 날",
      "knowledge.holiday.parents_day": "어버이날",
      "knowledge.holiday.may20": "520(5월 20일)",
      "knowledge.holiday.qixi": "칠석",
      "knowledge.holiday.teachers_day": "교사의 날",
      "knowledge.holiday.christmas": "크리스마스",
      "designDetail.evaluation.title": "플랜 평가",
      "designDetail.evaluation.rating": "평점",
      "designDetail.evaluation.feedback": "메모 / 고객 피드백",
      "designDetail.evaluation.placeholder": "고객 반응이나 디자인 과정의 메모를 기록하세요...",
      "designDetail.evaluation.saveBtn": "평가 저장",
      "designDetail.share.button": "고객에게 보내기",
      "designDetail.share.title": "디자인을 고객과 공유",
      "designDetail.share.hint": "링크를 메시지나 이메일로 보내세요. 고객은 가입 없이 보고, 그 자리에서 승인하거나 수정을 요청할 수 있습니다.",
      "designDetail.share.showPrice": "공유 페이지에 견적 표시",
      "designDetail.share.privacy": "공유 페이지에는 이미지, 꽃 소재와 수량, 설명, 매장 이름만 표시됩니다. 원가·이익·고객 정보는 나타나지 않으며 검색 엔진에도 노출되지 않습니다.",
      "designDetail.share.revoke": "링크 해제",
      "designDetail.share.revoked": "링크를 해제했습니다. 이전 링크는 즉시 사용할 수 없습니다",
      "designDetail.share.done": "완료",
      "designDetail.share.failed": "공유 링크를 만들지 못했습니다. 다시 시도해 주세요.",
      "designDetail.share.copyFailed": "복사하지 못했습니다. 직접 복사해 주세요",
      "designDetail.share.clientApproved": "고객이 이 디자인을 승인했습니다",
      "designDetail.share.clientChanges": "고객이 수정을 요청했습니다",
    ],
    .fr: [
      "productionSheet.title": "Fiche de fabrication",
      "productionSheet.stems": "{{n}} tiges",
      "productionSheet.minutes": "~{{n}} min",
      "productionSheet.recipe": "Recette",
      "productionSheet.col.flower": "Fleur",
      "productionSheet.col.role": "Rôle",
      "productionSheet.col.count": "Qté",
      "productionSheet.col.length": "Longueur de coupe",
      "productionSheet.col.stock": "En stock",
      "productionSheet.col.cost": "Coût",
      "productionSheet.role.main": "Fleur principale",
      "productionSheet.role.filler": "Fleur d'appoint",
      "productionSheet.role.foliage": "Feuillage",
      "productionSheet.notInStock": "Hors stock",
      "productionSheet.total": "Total",
      "productionSheet.retailHint": "Total aux prix de vente (indicatif, tige par tige)",
      "productionSheet.checks": "Contrôles avant fabrication",
      "productionSheet.check.allGood": "Aucun problème notable de stock, de budget ou d'équilibre",
      "productionSheet.check.stockShort": "Stock insuffisant pour {{name}} : {{need}} tiges nécessaires, {{have}} disponibles (manque {{short}})",
      "productionSheet.check.notInInventory": "{{name}} n'est pas dans votre stock (peut-être une suggestion de l'IA). Vérifiez que vous pouvez vous le procurer",
      "productionSheet.check.budgetOver": "Le coût matière de ¥{{cost}} dépasse le budget de ¥{{budget}}",
      "productionSheet.check.budgetUnder": "Le coût matière de ¥{{cost}} représente moins de 30 % du prix de ¥{{budget}} ; vous pouvez monter en gamme",
      "productionSheet.check.lowMargin": "La marge n'est que de {{margin}} %, sous le seuil habituel de 35 %",
      "productionSheet.check.noMainFlower": "Aucune fleur principale : le point focal risque d'être peu lisible",
      "productionSheet.check.foliageHeavy": "Les fleurs d'appoint et le feuillage représentent {{pct}} % ; peu de fleurs principales",
      "productionSheet.craft": "Points techniques",
      "productionSheet.container": "Contenant / emballage",
      "productionSheet.mechanics": "Méthode de fixation",
      "productionSheet.prep": "Préparation et conditionnement",
      "productionSheet.assembly": "Ordre de montage",
      "productionSheet.care": "Entretien et livraison",
      "productionSheet.priceProfit": "Prix de vente → bénéfice · marge",
      "knowledge.title": "Revue de composition",
      "knowledge.subtitle": "Contrôles fondés sur l'école, l'occasion et les connaissances florales (à titre indicatif)",
      "knowledge.loading": "Vérification…",
      "knowledge.allClear": "Aucun problème notable d'école, de culture ou d'équilibre",
      "knowledge.season.spring": "le printemps",
      "knowledge.season.summer": "l'été",
      "knowledge.season.autumn": "l'automne",
      "knowledge.season.winter": "l'hiver",
      "knowledge.rule.focalTypesMany": "{{n}} types de fleurs principales vont se disputer l'attention ; on se limite en général à 3 types au plus et on traite le reste en fleurs d'appoint ou en feuillage",
      "knowledge.rule.noSupport": "Uniquement des fleurs principales, sans fleurs d'appoint ni feuillage pour soutenir et structurer la forme",
      "knowledge.rule.noFoliage": "Aucun feuillage ; en ajouter dessinera et encadrera la silhouette",
      "knowledge.rule.mixedVaseLife": "{{name}} ne tient qu'environ {{days}} jours, bien moins que le reste ; livrez le jour même ou le lendemain et invitez le client à en profiter vite",
      "knowledge.rule.outOfSeason": "{{names}} n'est pas de saison pour {{season}} ; le coût peut être élevé ou la qualité irrégulière",
      "knowledge.rule.paletteBusy": "{{n}} familles de couleurs peuvent paraître brouillonnes ; envisagez de vous limiter à 2–3 familles dominantes",
      "knowledge.rule.tabooChrysanthemum": "{{names}} (chrysanthème blanc ou jaune) est associé aux funérailles dans de nombreuses régions, ce qui convient mal à une occasion festive",
      "knowledge.rule.strongScentComfort": "{{names}} est très parfumé et ne convient pas à une visite à l'hôpital ou à des condoléances",
      "knowledge.rule.tabooFour": "{{names}} est utilisé par 4 ; en chinois, japonais et coréen, « 4 » évoque « la mort », donc on évite souvent d'offrir 4 fleurs — pensez à 3 ou 5",
      "knowledge.rule.tabooFourTotal": "Le total est de 4 tiges ; en chinois, japonais et coréen, « 4 » évoque « la mort », donc on évite souvent ce nombre en cadeau",
      "knowledge.rule.schoolTooFewStems": "{{school}} demande généralement au moins {{min}} tiges pour tenir sa forme ; il n'y en a que {{n}}",
      "knowledge.rule.schoolTooManyStems": "{{school}} privilégie la retenue, généralement pas plus de {{max}} tiges ; il y en a {{n}}",
      "knowledge.rule.schoolTypesMany": "{{school}} fonctionne mieux avec peu de types de fleurs ({{max}} au plus) ; il y en a {{n}}",
      "knowledge.rule.schoolTypesFew": "{{school}} repose sur la richesse des associations ; visez au moins {{min}} types, il y en a {{n}}",
      "knowledge.rule.schoolNeedsFoliage": "{{school}} comporte normalement du feuillage (en collerette ou entremêlé) ; il n'y en a pas ici",
      "knowledge.rule.kbCoverage": "Ces fleurs ne figurent pas encore dans la base de connaissances, donc les contrôles de saison, de tenue et de parfum ne s'y appliquent pas : {{names}}",
      "knowledge.rule.petToxicSevere": "{{names}} est extrêmement toxique pour les chats (pétales, pollen et même l'eau du vase sont dangereux) ; ne pas offrir ni placer dans un foyer avec des chats",
      "knowledge.rule.petToxic": "{{names}} est légèrement toxique pour les chats et les chiens ; rappelez aux clients ayant des animaux de le placer hors de portée",
      "knowledge.rule.sapNarcissus": "La sève de coupe de {{name}} bouche les tiges des autres fleurs et raccourcit leur tenue ; laissez-le tremper seul 12 à 24 h avant de le mélanger, et ne le mettez jamais fraîchement coupé avec les autres fleurs",
      "knowledge.rule.pollenStain": "Le pollen de {{names}} tache facilement les robes et les vêtements ; retirez les anthères lors de la réalisation",
      "knowledge.rule.clientPetToxic": "Le client a des chats et {{names}} est très toxique pour eux ; à remplacer impérativement",
      "knowledge.rule.clientPetToxicMild": "Le client a des animaux et {{names}} est légèrement toxique pour les chats et les chiens ; remplacez-le ou conseillez de le placer hors de portée",
      "knowledge.rule.clientAvoid": "Le client a indiqué ne pas vouloir {{names}}",
      "knowledge.rule.clientScent": "Le client est sensible aux parfums forts et {{names}} est très parfumé",
      "knowledge.rule.clientPollen": "Le client est sensible au pollen et {{names}} en produit beaucoup ; remplacez-le ou retirez les anthères",
      "knowledge.rule.holidayPriceSurge": "{{holiday}} dans {{days}} jour(s) : le prix de gros de {{names}} monte souvent à {{low}}–{{high}} fois la normale — sécurisez le stock tôt et chiffrez au tarif de fête",
      "knowledge.rule.tabooNine": "{{names}} est utilisé par 9 ; en japonais, « 9 » (ku) évoque « la souffrance », on évite donc souvent d'offrir 9 fleurs au Japon — pensez à 7 ou 11",
      "knowledge.rule.tabooNineTotal": "Le total est de 9 tiges ; en japonais, « 9 » (ku) évoque « la souffrance », on évite donc souvent d'offrir 9 fleurs au Japon",
      "knowledge.school.japanese_ikenobo": "Ikenobo",
      "knowledge.school.japanese_ohara": "Ohara",
      "knowledge.school.japanese_sogetsu": "Sogetsu",
      "knowledge.school.chinese_literati": "Fleur de Lettré",
      "knowledge.school.chinese_zen": "Fleur Zen",
      "knowledge.school.western_biedermeier": "Biedermeier",
      "knowledge.school.western_english": "Jardin Anglais",
      "knowledge.school.fusion": "Fusion",
      "knowledge.badge.title": "Revue : {{error}} critique(s), {{warn}} suggestion(s), {{info}} note(s)",
      "knowledge.holiday.valentine": "Saint-Valentin",
      "knowledge.holiday.spring_festival": "Nouvel An chinois",
      "knowledge.holiday.womens_day": "Journée des femmes",
      "knowledge.holiday.white_day": "White Day",
      "knowledge.holiday.qingming": "Qingming",
      "knowledge.holiday.mothers_day": "Fête des mères",
      "knowledge.holiday.parents_day": "Fête des parents",
      "knowledge.holiday.may20": "520 (20 mai)",
      "knowledge.holiday.qixi": "Qixi",
      "knowledge.holiday.teachers_day": "Fête des enseignants",
      "knowledge.holiday.christmas": "Noël",
      "designDetail.evaluation.title": "Évaluation",
      "designDetail.evaluation.rating": "Note",
      "designDetail.evaluation.feedback": "Notes / Retour Client",
      "designDetail.evaluation.placeholder": "Enregistrez la réaction du client ou vos notes...",
      "designDetail.evaluation.saveBtn": "Sauvegarder",
      "designDetail.share.button": "Envoyer au client",
      "designDetail.share.title": "Partager cette composition avec votre client",
      "designDetail.share.hint": "Envoyez le lien par message ou e-mail. Votre client peut la consulter sans inscription et la valider ou demander des modifications directement.",
      "designDetail.share.showPrice": "Afficher le devis sur la page partagée",
      "designDetail.share.privacy": "La page partagée n’affiche que l’image, les fleurs et quantités, le texte et le nom de la boutique. Coûts, marges et données client n’apparaissent jamais, et la page n’est pas indexée.",
      "designDetail.share.revoke": "Révoquer le lien",
      "designDetail.share.revoked": "Lien révoqué — l’ancien lien ne fonctionne plus",
      "designDetail.share.done": "Terminé",
      "designDetail.share.failed": "Impossible de créer le lien. Veuillez réessayer.",
      "designDetail.share.copyFailed": "Copie impossible — copiez le lien manuellement",
      "designDetail.share.clientApproved": "Votre client a validé cette composition",
      "designDetail.share.clientChanges": "Votre client demande des modifications",
    ],
  ]
}
